### ISSUE TITLE
Input box for coordinates for Google Maps

### ISSUE THREAD

**Issue by baksteris** [impresspages/ImpressPages#446]
Add please Input field for coordinates/addreses for Google Maps. Sometimes  complicatedly find an needed place without auto search function. Thank you

**Comment by santo74** [comment]
I was referenced to this issue from #664
Unfortunately this ticket is mostly in a language that I don't understand, so can I ask what's the status of this ?

**Comment by maskas** [comment]
Everyone agreed that this is a welcome feature :), but noone has implemented it yet :)
So it has been forgotten for a while.

**Comment by santo74** [comment]
Ok, then hopefully it gets attention again now ;-)

**Comment by maskas** [comment]
Apparently it did.

**Comment by baksteris** [comment]
Thank you Mangirgai!

**Comment by maskas** [comment]
Finally :DDDDD

**Comment by santo74** [comment]
Wow, that's fast :+1:
