### ISSUE TITLE
Feature requests about Repository

### ISSUE THREAD

**Issue by afbora** [impresspages/ImpressPages#617]
I think, the weakest part of the ImpressPages is **Repository**. It should be improved. Some of the ideas in my mind:

1. **Showing file name:** Currently file names are showing in img title. It should be visible to find quickly.
2. **Switching view:** Currently files are showing as thumbnails. List, grid, big, small views should have.
3. **Custom sorting:** Currently files are sorting by date. Name, size, type, date sorts should be available.
4. **Folders and groups:** I can confuse even picture since very few. Should have folders or groupping method.

Repository is one of the most important elements for clients/customers. It should be clear and useful to manage website. When the number of pictures a little more, people are struggling.

Thanks

**Comment by baksteris** [comment]
+1
I agree,  in repository must be more user friendly, with preview, I think many users needed possibilities sorting files by folders (by needed) eg. Logos, photos, docs, not sorted and etc.

**Comment by feniweb** [comment]
For a CMS with these skills, it is essential to be able to store images in folders.

And multiple processing would not be bad.

**Comment by smitti** [comment]
I agree with feniweb: to store images in folders is a 'must have' for impresspages.
