### ISSUE TITLE
Allow access to plugin options for user without "plugins" access

### ISSUE THREAD

**Issue by donnysim** [impresspages/ImpressPages#651]
In most cases, the plugins section is disabled for "editor" accounts so that the client can't mess with the plugins, but it also gives a problem because certain plugin settings should be accessible for them. Would it be possible to mark certain options like `public: 1` and push them to settings section? The list doesn't need to have tabs, a simple list with plugin name\custom separator would suffice.

For example having the plugin options:

```
    {
        "label": "Default image height",
        "name": "imageHeight",
        "type": "text",
        "default": "300",
        "public": 1 // default would be 0
    }
```

**Comment by feniweb** [comment]
Thank you again for the quick response.
On the problem with the image plugin.

The width is OK. Only the height of the picture is different in each case as they are changed proportional. Yes I know I can adjust but that is to be tested with many connected. here would be an excellent example of fixed input All pictures are said to have 150px height.
Or you want to Square picture.

See image with a proposal. 2 input fields for height and width. Are great.
![Image 2 input fields](http://d4m.ch/imp/file/2014/12/10/Zuschneiden_2__2.jpg)

I believe in a Previous Version, there was the one time.
Thank you for increasingly better CMS.

**Comment by maskas** [comment]
I'm thinking of replacing the current image cropping tool with one of these: http://www.jqueryrain.com/demo/jquery-crop-image-plugin/

the one that would show the whole picture and you just select the part you would like to crop. In addition to that, your proposed input fields would play very well as user would understand clearly what those inputs do. 

Using current cropping tool, changing the dimmensions would change the view and that may lead to multiple strange user experience problems. 

What do you think? Which tool do you like the most out of that list? It would have been so nice to raise this as a separate issue. Now it is hard to ask other users for their oppinion.

**Comment by maskas** [comment]
I've created a separate ticket https://github.com/impresspages/ImpressPages/issues/658

could we close this one?

**Comment by HalcyonD** [comment]
This one is of topic :octocat: . 

If we're back to the original question, why wouldn't something similar to the "permissions" handling work? A tabbed interface for dealing with user permissions/plugin settings permissions. You print all available plugin configs (would need some kind of grouping together), when you tick one, it creates an entry for that user in its specific table. "key" could be the same as it is saved in "ip_storage". If the user has at least one available plugin setting, maybe show a "Settings" section with the allowed plugin settings (filtered from plugin options).

This maybe could be extended to add individual widget access.

**Comment by maskas** [comment]
Sure it is. But we reach the complexity that's going to be hard to implement and hard to use. 

plugin permissions x plugin options configuration permissons x granular page permissions x other granular permissions of other plugins x users count  = innormos complexity 

We need a smart implementation for that. The one that could be easily implemented, comfortable to use and flexible.

**Comment by Worldwebdesign** [comment]
Any progress been made on this. I have been working on roles based permissions for pages and plugins and so far it is proving to be more complex than I would have thought. I have worked with and developed on many systems that use role based permissions for viewing and editing of content on a site but this time am finding it hard to get this to work without slowing down the system. And did not actually realise that you are some of the way there with the administrator super admin toggle button. Where are these values held.

**Comment by HalcyonD** [comment]
It should slow down only for admin, no? so it shouldn't really matter for users imo.

**Comment by Worldwebdesign** [comment]
I am trying to make it so if a user logs in and they are a member of a group called web customers then they will only see pages for their group and so on and so forth. Similar to DNN as their user roles management was awesome. Just pitty it runs on windows.

**Comment by maskas** [comment]
No real progress on this task. Just a confirmation, that we are heading this way.

Please create separate issues for subjects like granuler permissions.

**Comment by Worldwebdesign** [comment]
So you are going to add at some point permissions into impresspages. If this is the case I will share on another section my findings issues and project brief I put together for permissions.

**Comment by maskas** [comment]
Oh sorry. That image has missled me. No plans to introduce something regarding permissions. So your comments are in the right place. My comments are irrelevant :)

**Comment by Worldwebdesign** [comment]
O ok. thanks. So no plans at all for permissions.

**Comment by maskas** [comment]
I would love to see granular permissions happening. But it is a huge work. And I don't see any it coming in near future. 

By the way, I never seen anyone suggesting a good interface for it either. They are always very specific (just for specific cases), or very complex or nearly impossible to implement.

**Comment by HalcyonD** [comment]
I think in suck case IP would benefit from something like Eloquent, sure, it would slow down the app but it's nothing compared to the time you'd save and the flexibility you'd have. It's something that I miss in IP when working with DB :\ Maybe in IP5? :D

**Comment by maskas** [comment]
You can use Eloquent or other ORM. It shouldn't be integrated to be used. Use any you like.

**Comment by HalcyonD** [comment]
But most of the time that would mean opening a second connection to the database which is not something I'd want to do. In addition, it would provide support for mysql, postgres, sqlite, etc. with no hassle when updating etc.. it's just something to think about.

**Comment by maskas** [comment]
ImpressPages supports SQLite. There is a contribution of postgres, but not
stable. I guess you can reuse the same connection. It depends on
capabilities of that particular ORM system. I don't see issues to introduce
Doctrine, Eloquent, etc. plugins.






*Mangirdas Skripka*
mangirdas@impresspages.org
+37067128095

www.impresspages.org

Become our fan on Facebook <http://www.facebook.com/ImpressPages> and
follow us on Twitter <http://www.twitter.com/ImpressPages>
