### ISSUE TITLE
Improve title in subgrid

### ISSUE THREAD

**Issue by linksblinker** [impresspages/ImpressPages#654]
When entering a subgrid, title as defined in subgrid configruation is shown. To make editing clearer It would be nice additionally to see a specific field of parent dataset.

Old behavior - user can´t see anything of parent dataset:
![bild1](https://cloud.githubusercontent.com/assets/7022474/5619976/6cd92b5a-9527-11e4-99ba-c9ee2058c826.JPG)

Suggested behavior - user can see title of parent dataset:
![bild2](https://cloud.githubusercontent.com/assets/7022474/5620019/e40995f2-9527-11e4-9e11-72e7ac5a3f3a.JPG)

**Comment by maskas** [comment]
Wouldn't it be the same "Tagesstatten" value that's visible in the breadcrumb?

**Comment by linksblinker** [comment]
No, thats the point. "Tagesstätten" is the title of the parent grid, but not of the parent dataset, from which the subgrid ist called from.

In mastergrid "Tagesstätten" subgrid "Pictures"  assigned to all datasets:
![bild3](https://cloud.githubusercontent.com/assets/7022474/5625227/2a21b692-9577-11e4-99d3-422b3b280308.JPG)

After entering a subgrid of a single dataset (for exampe "Testkindergarten") to editing detail-picturedata, user can´t see anymore, which dataset he is editing. In breadcrumb he can only see, he is editing a subrgid of any dataset from mastergrid "Tagesstätten" but not the the particular dataset "Testkindergarten". So it would be nice, if information of the particular dataset can be shown in subgrid. 

This might be in the title of subgrid
![bild4](https://cloud.githubusercontent.com/assets/7022474/5625240/7ec5d11a-9577-11e4-8432-73ad7517ac5e.jpg)

or in breadcrumb
![bild5](https://cloud.githubusercontent.com/assets/7022474/5625368/d376915c-9579-11e4-8e02-ef27d7b3643b.jpg)

**Comment by maskas** [comment]
Do you know 'breadcrumbField' setting (https://www.impresspages.org/docs/grid)?

Isn't it exactly what you are loooking for?

**Comment by linksblinker** [comment]
I´didnt seen that... and yes, its exactly what im looking for :-)

Thanks for the advice! (and please close the issue)
