### ISSUE TITLE
Add pagination to the menu management section of the admin panel

### ISSUE THREAD

**Issue by mateoprifti** [impresspages/ImpressPages#655]
Hello ImpressPages team! i really like ImpressPages keep up the good work! :)
This is more of a proposal and request. I have noticed that ImpressPages doesn't feature pagination of some sort on the menu management section in the admin area. For example.. lets say we have a menu of type "List (used for blog entries)". If this menu get populated with lots of entries with time going by we might run on some load time issues and even site crashes when we visit that section of the admin panel. I think the best way to tackle this issue is to add some sort of pagination and/or lazy loading features(In this case by "lazy load i mean loading content as you scroll". Hope such feature get implemented soon as it is really use-full for content heavy websites. 

![impresspages-feature request](https://cloud.githubusercontent.com/assets/3778453/5621207/9d6e4578-9533-11e4-90aa-427a68b0d37e.png)

Best Regards

**Comment by maskas** [comment]
The paggination will appear when you will have more records. I don't remember what page size is set by default.

**Comment by mateoprifti** [comment]
Oh, cool then! I remember once asking this question at the old ImpressPages support page one month and a half ago and the reply was that there is no such feature. Is this a new feature in that comes with the latest update?

**Comment by maskas** [comment]
Yes. It was released recently.

**Comment by mateoprifti** [comment]
Oh ok, it is all clear then. I am closing this issue, thanks
