### ISSUE TITLE
In the Forms not work "Radio"

### ISSUE THREAD

**Issue by baksteris** [impresspages/ImpressPages#659]
Error in the Forms. After creating a form with "Radio", there is no radio functions, only the text of the title. Tested in the cloud impresspages so the same.
**************************
Klaida kuriant Forma. pasirenkant funkcija "Radio" atvaizduojamas tik pavadinimas, bet pacios funkcijos "Radio" nera. Pratestuota taip pat ir Impresspages debesyje, ta pati klaida.

**Comment by maskas** [comment]
Have you really selected some values in field options box? That's a good poing we probably have to add few default values to select from as otherwise the field is empty untill you fill in the values.

**Comment by baksteris** [comment]
Sorry, you are right Mangirdai :) I forgot to fill settings in one of the functionals in right site of Form. All is right and functionally

**Comment by baksteris** [comment]
Nevertheless, problems with the "radio" exist. By default should be so, when is several buttons "Radio", must be possible choose only one option. At the moment, you can select all the options. This is not correct for "Radio", since for this is "checkbox, where all cells is selectable.

One more problem in Firefox 34, i think it problem have only me. In Firexox 34 is not shown in the text editor "option Field '" checkbox ". Testing In IE-11, everything is OK. i use Win8.1. 
But, in demo site of Inpresspages this is not a problem, this problem is only on my site.
I tried to copy all files IP442, but the error remains. may be someone have any thoughts? :)

**Comment by baksteris** [comment]
P.S. maybe will be possible in "Forms" add one more variant of Fields - "Heading"? Sometimes this need for Heading one of the group inside of general Questionnaire. Thank you

**Comment by maskas** [comment]
Can't confirm this:

"Nevertheless, problems with the "radio" exist. By default should be so, when is several buttons "Radio", must be possible choose only one option. At the moment, you can select all the options. This is not correct for "Radio", since for this is "checkbox, where all cells is selectable."


It is working fine in my test http://3872.cloud.impresspages.org/

**Comment by baksteris** [comment]
By your link in your demo all work correctly.
I not understand, why this not work in my demo?
Test this please, and tell me, for you this working correctly?  http://3319.cloud.impresspages.org/home?_revision=4

**Comment by maskas** [comment]
You have created three radio button fields. Instead of creating one radio button field with three options.

**Comment by baksteris** [comment]
Hm, now i understand, thank you Mangirdai, and so sorry for this my mistake

**Comment by maskas** [comment]
No problem. Master branch already has a "Heading" field in form widget. Enjoy.

**Comment by baksteris** [comment]
Super, thanx, you are the best! ;)
