### ISSUE TITLE
Improve SEO friendly url generator algorithm

### ISSUE THREAD

**Issue by mateoprifti** [impresspages/ImpressPages#662]
Hello, i haven noticed something strange lately with with SEO friendly url generator when you create a new page. If the URL has a plus inside of it, for example if we have a page title of "Order now DVD + MOVIE" the generated url would look something like this " /order-now-dvd-+-movie " and when i click edit content a 404 page appears. However when i remove the plus from the url i can travel to that page with no problem. Please look in to this because it might cause trouble for people in the future. 
Thank you for the amazing job you've done with ImpressPages. Regards.

**Comment by maskas** [comment]
Thanks. Will have a look.

**Comment by jankus** [comment]
Similar things happens with comma. It should be removed from URL.

**Comment by maskas** [comment]
We have two separate problems over here:

1. If user enter "something+something", he gets "something-+-something". There is no question, user will be happier getting "something-something". This bit is easy.

2. If user enters a special symbol in a URL field (e.g. + %, etc.). How the system has to bihave. We can scream it is an in valid URL or we can encode using following line:

$path = implode('/', array_map('rawurlencode', explode('/', $this->urlPath)));

Then we don't care what the user enters. Url's always work.

But it will be executed on each link on the page on each pageview (if there is no cache). So on an average website it is about 20 times per pageview. 
We can store escaped URL in the database alongside original URL. In that case we won't have any performance hit.

The question I don't have an answer yet is do we want to allow user to enter + %, etc. in URL field. In theory there may be situation when that is needed. But has to be very rare.

**Comment by maskas** [comment]
Found an optimized version of the script. So users can use whatever URL they want :DDD
