### ISSUE TITLE
wrong path for logo

### ISSUE THREAD

**Issue by santo74** [impresspages/ImpressPages#663]
A wrong path is being used for the logo image in the logo slot

If I look at the image info In the logo editor, the path is http://localhost/file/repository/logo.png but in the site itself the image can't be loaded.
Viewing at the source reveals that a wrong location is inserted for the logo:
```html
<a href="http://localhost/" style="color: rgb(0, 0, 0); font-family: Arial,&quot;Helvetica Neue&quot;,Helvetica,sans-serif;" class="navbar-brand">
        <img src="http://localhost/file/2015/01/10/localhost.png" alt="localhost">
    </a>
```

**Comment by maskas** [comment]
This looks correct. '../repository/logo.png' is an original file.  'file/2015/...' is a resized / croped version for displaying on your website. The fact that it doesn't load means your website can't crop it properly. Have a look at System -> Log for any errors to generate that file.

**Comment by santo74** [comment]
Allright, that might be an explanation of course.
However I can't find anything related to the logo file in the log entries.
I'll try to upload it again and have a look in the server logs as well...

**Comment by santo74** [comment]
I cleared the log and then uploaded a new logo, but there are no entries at all in the log.
Also on the system level (nginx, php) there are no new entries.

So I don't know what's going wrong with the upload/cropping of the image.

**Comment by maskas** [comment]
If error is not visible in the logs, then first please make sure you have error display enabled in config.php. 
Then visit http://localhost/file/2015/01/10/localhost.png in the browser. If file won't open, press File -> Save as. and save that file with a .txt suffix. Open that file with the text editor. You should see an error.

**Comment by maskas** [comment]
By the way. Are there any issues with other images? Like image gallery, etc?

**Comment by santo74** [comment]
Ok, I'll try that.
I haven't used the image gallery yet. This is my first site with ImpressPages and I only started working on it yesterday ;-)
BTW, I'm really loving the concept of IP so far!

**Comment by santo74** [comment]
I ensured showErrors is enabled in config.php, tried to load the image as suggested and then saved the resulting page as a txt file, but the endresult is just a txt file that contains the 404 source code (as can be expected) without any additional info:

```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Actually this seems obvious to me, as the problem apparently occurs on the backend (i.e. not cropping during upload of the image for some reason) and not during display in the frontend (this is just a 404 as a result of the missing cropped file).

BTW, I also tested with the image gallery and that's exactly the same.

So whenever I upload a file, being it a logo, an image for a gallery or whatever, the thumbnails aren't generated and consequently the file repository as well as the site itself (logo, gallery, ....) can't show the image(s).
FYI: The file repository also doesn't show the thumbnail of an image after uploading it.

So the question remains: why aren't the images being cropped ?
Given the fact that I don't see any error messages related to the cropping of the image(s) it seems more like the cropping is never being triggered for some reason.
I'm not saying that is the case, but that's the impression I get because of the missing log entries.

**Comment by maskas** [comment]
Now I know exactly what's wrong. You haven't setup Nginx properly. Here are the instructions:

https://www.impresspages.org/help/nginx?qa-rewrite=419/impresspages-on-nginx-webserver

Either yo do this or disable nice URLs in config.php by entering rewritesDisabled setting with value 0.

By the way, these instructions should have been shown to you during the installation process.

**Comment by santo74** [comment]
My Nginx is configured as per the instructions on that page, but because I'm also using php-fpm I have some additional entries in there.

Actually I first investigated whether IP could run under nginx and what it would take me to do before I actually started installing it, so I didn't get that info during installation because it was already properly configured.

But I just did a test over https and that is working!
So I probably have to investigate my nginx configuration in more detail as there seems to be a difference in behaviour between http and https.

**Comment by maskas** [comment]
The part that rewrites non existing (SEO friendly) URLs to index.php doesn't work on your server. This is the case you have to focus to.

Alternatively you can add rewritesDisabled => 1 to the config.php file

**Comment by santo74** [comment]
Ok, I found the culprit.
There is an extra rule for static files and images/movies to serve them directly rather than going through php-fpm, but apparently that rule needed some tweaking for IP.

**Comment by maskas** [comment]
That's probably because ImpressPages assets are cropped in real time on demand. 

for others, who have problems with assets being created in real time on deman, that feature can be turned off using setting realTimeReflections https://www.impresspages.org/docs/repository
