### ISSUE TITLE
A way to compress images

### ISSUE THREAD

**Issue by donnysim** [impresspages/ImpressPages#666]
ImpressPages needs a way to compress the uploaded images + a way to do so via Reflection (compress only option). Maybe then users won't complain when they upload 2MB images and it loads so slowly :/ Though I don't know what would be the best way to implement this.

**Comment by HalcyonD** [comment]
Is there an event you can catch on image upload?

**Comment by maskas** [comment]
Which images are we talking about? As they are compressed. Which particular part users are complaining about? Is it like gallery images on the website appearing as content? Or do they experience slowdown browsing the repository? Or maybe uploading their own assets? I the slowdown felt all the time or only for the first time?

**Comment by HalcyonD** [comment]
Clients usually upload images straight from mobile or camera which results in huge images, I guess they could be resized. They place it in content and gallery, but I usually have a separate plugin for storing galleries so an event would be nice to intercept the image and resize/compress it (but that would solve only one side of the problem). 

So in the end if they upload 10 images, it's ~20MB and more to load (clients don't listen to things like "resave the image to reduce size" :\ ). Gallery isn't really the big problem as you usually make thumbnails for them but on the content side, it's different. 90% of the time it's via tinymce editor, which most likely is difficult to approach?

**Comment by maskas** [comment]
That's why default ImpressPages configuration doesn't allow image upload via TinyMCE. If you use additional plugin to enable image upload via TinyMCE, you are facing the consequences of this action. User must be smart so use TinyMCE instead of default ImpressPages widgets.

**Comment by TheFOBas** [comment]
My implementation of TinyMce repository plugin is able to resize images to given size. http://market.impresspages.org/plugins/TinyMceRepository But in reality just teach the users to use columns and they will be able to deal with most of the scenarios involving images.

**Comment by maskas** [comment]
I never give full featured TinyMCE to the client. If there are any specific needs, that can't be covered by columns, I create a widget for that.
