### ISSUE TITLE
Problem with ImpressPages 4.5.0 with theme Bootstrap Free (1.00)

### ISSUE THREAD

**Issue by fredrikl78** [impresspages/ImpressPages#675]
It's not possible to edit the "logo" of the site or "select a link target" when inserting a link into a text on the site. The popup windows that are displayed are grayed out and it's not possible to change anything in them. The same problem might occur in more places where popup windows are opened.

The problem described above did not exist with Impresspages 4.4.2 and earlier in combination with the theme Bootstrap Free (1.00). With the default theme there is no problem. This is tested on Firefox and Chromium on Linux and on Internet Explorer and Firefox on Windows. Also tested on different servers with the same result both with a new installation of version 4.5.0 and a upgraded one.

**Comment by wannaco** [comment]
We were able to fix that bug and the theme has been updated in the market place. We could not communicate to all of the Bootstrap Free theme users, Feel free to contact us.

**Comment by wannaco** [comment]
By the way the fixed theme was approved at 5:54 AM  CST  Monday January 26th

**Comment by fredrikl78** [comment]
Thank you very much for the fix. I can confirm that it's working with "select a link target" now but it's still not working with the "logo" of the site. With the "logo" I mean the one that is shown at the upper left most corner of the theme Bootstrap Free (1.01). It's not editable for me at least.

**Comment by wannaco** [comment]
We'll look into that and update the thread when it has ben fixed

**Comment by jankus** [comment]
It's not related to the core of ImpressPages. I'm closing this issue as this issue should be fixed by theme author in theme directly.

**Comment by wannaco** [comment]
Fredrik,

We have updated the theme to Bootstrap 3.3.2 and awaiting approval so you sould be able to update the theme as soon as its approved.

**Comment by maskas** [comment]
Done

**Comment by fredrikl78** [comment]
Thank you very much. It works really good now.
