### ISSUE TITLE
Active plugin underline on hover

### ISSUE THREAD

**Issue by maskas** [impresspages/ImpressPages#678]
![strange underline2](https://cloud.githubusercontent.com/assets/1159983/5899309/456f5134-a562-11e4-9cef-d6dca61fd4b4.png)

**Comment by maskas** [comment]
It looks like this is the way AngularJS works until you click somewhere else.

**Comment by jankus** [comment]
AngularJS just keeps element "on focus". Which means in CSS you need to style both "hover" and "focus" pseudo classes.
