### ISSUE TITLE
Incorrect modal backdrop height

### ISSUE THREAD

**Issue by donnysim** [impresspages/ImpressPages#680]
When the form is long, and that will always be the case with multilang, the first time you edit an entry (seems to be the case only for edit action), the backdrop has incorrect height.
![incorrectbackdropheight](https://cloud.githubusercontent.com/assets/8076512/5954170/7b236d06-a79c-11e4-9d6e-df59ae015102.jpg)

If you close it and open it again, it fixes it. I assume it's because the modal isn't fully loaded with content before setting the backdrop height.

**Comment by maskas** [comment]
I guess this is related https://github.com/impresspages/ImpressPages/issues/677

**Comment by HalcyonD** [comment]
I have the scroll fix applied and it's only visible when you scroll down.

**Comment by maskas** [comment]
Ok. got it.

**Comment by jankus** [comment]
No, they're not related. Here's the issue that modal loads, calculates everything by content and later on our JavaScript adds WysiWyg which makes form longer.

**Comment by jankus** [comment]
I can confirm that. Bootstrap modal before opening calculates content height and sets backdrop height. Since we load WYSIWYG after modal opening we get that issue.

This means that each script that modifies content should check whether it's in a modal and modify backdrop accordingly.
