### ISSUE TITLE
Display page via route, without redirect

### ISSUE THREAD

**Issue by HalcyonD** [impresspages/ImpressPages#683]
Is there a simple way to return a page via route?

For example, there is a page with url '/lorem-ipsum', but I want to return that page via a route '/test'.

My current code is:

    $page = ipContent()->getPage(16);
    $revision = \Ip\Internal\Revision::getPublishedRevision($page->getId());
    
    $isBlockStatic = false;
    
    if ($isBlockStatic) {
        $languageId = ipContent()->getCurrentLanguage()->getId();
    } else {
        $languageId = 0;
    }
    
    ipContent()->_setCurrentPage($page);

    return \Ip\Internal\Content\Model::generateBlock('main', $revision['revisionId'], $languageId, ipIsManagementState(), '');

I don't want a redirect, but to just display that specific page via a different url.

Edit: and keep the ability to edit the content and drag widgets.

**Comment by maskas** [comment]
Creating a 'ipRouteAction' Job in your plugin with the content similar to this may work. Haven't tested. :



    public static function ipRouteAction($info)
    {
        if ('something')  {
            $result['page'] = new \Ip\Page($page);
            $result['plugin'] = 'Content';
            $result['controller'] = 'PublicController';
            $result['action'] = 'index';
            return $result;

        }

    }


I will have a look if the same could be done in the controller.

**Comment by HalcyonD** [comment]
Welp, that works and simplifies it quite a bit :O t.y. :+1: maybe in the future it could be implemented in the routes, to work in the similar fashion but if the returned object is Page? 

    $routes['test'] = function() {
        return ipContent()->getPage(16);
    };

**Comment by maskas** [comment]
It looks like you set the page setting in your route

'page' => ipPage(pageIdOrAlias)

and following content in your controller action

        $revision = \Ip\ServiceLocator::content()->getCurrentRevision();
        if ($revision) {
            return \Ip\Internal\Content\Model::generateBlock('main', $revision['revisionId'], 0, ipIsManagementState());
        } else {
            return '';
        }


Then everything is working.

**Comment by maskas** [comment]
By the way, because ImpressPages routes are plane PHP files, you can use some algorithm and return different page object depending on some circumstances.

**Comment by HalcyonD** [comment]
Thanks for the help!

**Comment by HalcyonD** [comment]
Am I missing something or does the widgets only appear when you have the ipRouteAction return array with ['page'] element? Otherwise, no matter what you do, the widgets bar is hidden. The controller is the last thing it executes which is way after everything is prepared for the page.

**Comment by HalcyonD** [comment]
Would be nice if you could pass a function to the page parameter in the same way you can for `action` :O

**Comment by HalcyonD** [comment]
:dizzy_face: I just answered my own question :D

**Comment by maskas** [comment]
You have answered your own question, but the problem still exists right? You had to do the URL parser in routes.php file?

**Comment by HalcyonD** [comment]
I just manually called `\Ip\Internal\Content\Helper::initManagement();` in the controller after `ipContent()->_setCurrentPage($page);` but now I noticed that the publish button is not present so I'm still few steps away from completing solution :\

**Comment by maskas** [comment]
Ip\Internal\Content\Event.php implements ipBeforeController event. Important javascripts are being added in this event. Not sure if that's the only bit missing.

The best solution would be to refactor widget initialization to be done after controller instead of before controller. But that could be not so easy. So instead of forcing management state in your controller, I would better go for parsing URL in routes.php. That would be a smaller evil, I think.

**Comment by HalcyonD** [comment]
I probably solved it by just placing a dummy page in the 'page' param and then in the controller:

    $page = ipPage($pageId);
    ipContent()->_setCurrentPage($page);
    ipSetLayout($page->getLayout());
    $revision = \Ip\ServiceLocator::content()->getCurrentRevision();
    \Ip\Internal\Content\Helper::initManagement();
    return \Ip\Internal\Content\Model::generateBlock('main', $revision['revisionId'], 0, ipIsManagementState());

**Comment by maskas** [comment]
:) nice cheat.
