### ISSUE TITLE
Development Workflow

### ISSUE THREAD

**Issue by Jayshua** [impresspages/ImpressPages#687]
Sorry if this is the wrong place for this question, but I'm rather new to full scale PHP development, and am wondering what the workflow for Impress Pages looks like. How do you connect it to the development database? I assume you have some kind of local configuration file set up? How exactly is that loaded by Impress? And how do you keep things specific to your development environment from the repo (is /file in the .gitignore enough?) Last, what exactly is composer doing, as it doesn't look like you have any dependencies? Again, sorry if this is the wrong place for this question. Thank you for your time!

**Comment by maskas** [comment]
Don't worry about the composer. Composer is there just to make ImpressPage available as a package for Symfony. 

Files and config.php usually are added to .gitignore, while all other files go to GIT.

That's probably all.

**Comment by Jayshua** [comment]
So you just setup a config.php file (the one under the install directory?), populate the database, and everything runs? Just code then? I guess I'm not used to how little a PHP install script actually does. The part I'm having trouble with (understanding) is the state difference between source code (need to be "installed") and actually running (is "installed"). Is there no difference at all, so it doesn't matter? Do you often reload the database during development? If so do you reinstall the system like a user would, use index.php under "install", or something else entirely? Sorry if I'm asking too many questions...

**Comment by maskas** [comment]
Installation script does just two things: 

1. Populates the database
2. Writes config.php file

After isntall, just remove install directory. You don't need to run it again. But if you want a clean database after the development, you can remove the database, remove the content from config.php and rerun the install.

**Comment by Jayshua** [comment]
Ok that makes sense. Thank you!
