### ISSUE TITLE
500 Internal Server Error.

### ISSUE THREAD

**Issue by Worldwebdesign** [impresspages/ImpressPages#694]
Hi I have moved all my sites to a new service provider as my old one let me down to many times. But we got everything up and running great and then we are getting a 500 Internal server error on one which happens to be the one Multisite is installed on and about 50 sites. All the other standalone sites are fine just this one that seems to have the error.

**Comment by Worldwebdesign** [comment]
we know it is loading the run.php file as we put a html comment in it just to see but I think it is failing to load the applications.php after that.

**Comment by maskas** [comment]
Have a look what is that error. It should be visible in Apache logs.

**Comment by Worldwebdesign** [comment]
This is the error code we are getting we have replaced the main directory and domain names.

PHP Fatal error:  Uncaught exception 'Ip\\Exception\\Db' in /data/www/domain/Ip/ServiceLocator.php:257\nStack trace:\n#0 /data/www/domain/Ip/Db.php(28): Ip\\Db->getConnection()\n#1 /data/www/domain/Ip/ServiceLocator.php(257): Ip\\Db->__construct()\n#2 /data/www/domain/Ip/ServiceLocator.php(226): Ip\\ServiceLocateLocator::loadService('db')\n#3 /data/www/domain/Ip/Functions.php(378): Ip\\ServiceLocator::db()\n#4 /data/www/domain/Plugin/MultiSite/Model.php(263): ipDb()\n#5 /data/www/domain/Plugin/MultiSite/Service.php(40): Plugin\\MultiSite\\Model::getWebsiteByDomain('domain.com', false)\n#6 /data/www/domain/Plugin/MultiSite/run.php(38): Plugin\\MultiSite\\Service::getWebsiteByDomain('domain.com', false)\n#7 /data/www/domain/index.php(3): require_once('/data/www/twigg...')\n#8 {main}\n  thrown in /data/www/domain/Ip/ServiceLocator.php on line 257, referer: http://domain.com/

**Comment by maskas** [comment]
It can't connect to the database.

**Comment by Worldwebdesign** [comment]
Ok well that is strange as nothing has changed and it had a connection yesterday
I will try resetting the user and password

**Comment by Worldwebdesign** [comment]
Found out why it happened now need to fix it. everything is the same as our old server this is just faster and it is setup the same. The issue is when multisite creates a new database in mysql it is creating a new user with the same name as the original one but with no rights only rights to the new database that was created. As soon as I deleted this new user the sites all came back online
