### ISSUE TITLE
Page list filter

### ISSUE THREAD

**Issue by HalcyonD** [impresspages/ImpressPages#695]
Could we add pages list filter to the `JsTreeHelper@getList` like `$pages = ipFilter('ipGetPages', $pages);` so we could hide or modify specific pages before returning the list?

**Comment by maskas** [comment]
Are we talking about page list / tree in pages management section?

**Comment by HalcyonD** [comment]
Yup.

**Comment by maskas** [comment]
Here you have it in develop branch

https://github.com/impresspages/ImpressPages/commit/92e0da2204d54455d55a095edd0d2569e6a9bfec
https://github.com/impresspages/ImpressPages/commit/26757e646835c5b0d8088d17e926725f18cbcb03

**Comment by HalcyonD** [comment]
Thanks !

**Comment by HalcyonD** [comment]
I just got to use it and I noticed that the tree doesn't contain anything specific to the pages :\ for example I want to check `alias` or `isVisible` but I can't. Having an original page list before it getting parsed into a tree would work.

**Comment by maskas** [comment]
To make it work faster actual object are not being created. If you need, you can create an object. Especially if you have just few pages in your menu.

**Comment by HalcyonD** [comment]
Well, for the moment, in `JsTreeHelper` I have:

      protected static function getList($languageCode, $parentId)
      {
             $pages = ipDb()->selectAll('page',  '*', array('parentId' => $parentId, 'isDeleted' => 0), 'ORDER BY `pageOrder`');

             $pages = ipFilter('ipPages', $pages);
      ....

And this allows me to do what I need so far (read various values and remove pages if needed).

**Comment by maskas** [comment]
I don't understand what does the "JsTreeHelper" mean. Is it your own plugin or so? Of I have forgotten about some stuf we have built for ImpressPages? And does it mean implemented filters work fine for your or not?

**Comment by HalcyonD** [comment]
It's a class in IP that generates the structure for the tree `\Ip\Internal\Pages\JsTreeHelper.php`. So far the filter works and provides everything I need.

**Comment by HalcyonD** [comment]
Though I don't think this is the only place it should have the filter? Can't check right now, but maybe there should be one when generating menu?

**Comment by maskas** [comment]
If it works for you, I guess I can close this ticket. If you don't like the way menu slot generates the menu, you can use your own view file or fetch pages on your own.

**Comment by HalcyonD** [comment]
But there is no filter as  `$pages = ipFilter('ipPages', $pages);` in it, I added it, so maybe it could also be added to the IP? :O

**Comment by maskas** [comment]
What do you mean added? Where you have added it? On your own website?  Could you show how does your solultion looks like?

**Comment by HalcyonD** [comment]
`JsTreeHelper` class `getList` [function](https://github.com/impresspages/ImpressPages/blob/master/Ip/Internal/Pages/JsTreeHelper.php#L24) does not have the line by default:

    $pages = ipFilter('ipPages', $pages);

I added it and catch the filter in my plugin:

    public static function ipPages($pages) {

        foreach ($pages as $key => $page) {
            if ($page['alias'] === 'contest') {
                unset($pages[$key]);
            }
        }

        return $pages;
    }

**Comment by maskas** [comment]
I'm sorry I got your idea just now. It is not the kind of filter I would like to add. It is in a protected function. Highly depends on implementation. I'm not sure if that won't be changed in the future. If you could tell me what are you trying to do, maybe I can find another way  to implement it? Or refactor the whole thing in some different structure?

**Comment by HalcyonD** [comment]
Basically I have a Contests page and a plugin that adds sub pages to it and provides additional configuration for them. The problem I have now is that I don't want to show these sub pages in the admin pages menu as to not allow the user to accidentally delete one, not show them in the site menu and to prevent the possible clutter. Maybe an additional table column could solve this, something that would be easy to tell that this page is controlled by a plugin and should not be visible in any place.

**Comment by maskas** [comment]
This filter should work for you just fine: ipPageTree.

If there is any data missing in this event, use IDs to sort things out. You can store ids of pages that are created by your plugin somewhere in the database or so.

I'm still looking at your two previous contributions. I haven't forgotten them. I hope I will be able to further improve your fixes.
