### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by Worldwebdesign** [impresspages/ImpressPages#699]
Hi Guys,

Just wondering if anyone else has hit this issue. We are developing some plugins on a local development environment and require SSL to make sure everything works with SSL. However IP is not playing as it keeps giving us an error. They are self assigned IP's as they are local development installs.

Cron.failedFakeCron
array(3) { ["result"]=> string(0) "" ["type"]=> string(4) "curl" ["error"]=> string(48) "SSL certificate problem: self signed certificate" }

Any help much appreciated.

**Comment by maskas** [comment]
First you can turn off fake cron and use real cron.

Or use the fix I've just made. Please report if that works for you.

**Comment by Worldwebdesign** [comment]
there is no off switch in ip4 and yes I am no longer getting errors in the log. However I can not install any new plugins via the market place as when I click add plugin the page is blank same goes for the browse themes. these are just what we have found so far are with ssl.

**Comment by maskas** [comment]
There is an off switch. And it is in Admin -> Config -> Advanced section.

Other issues, I guess, are not related to SSL. Just turn on error reporting.

**Comment by Worldwebdesign** [comment]
All i see is excute cron automatically

**Comment by maskas** [comment]
Yes. So turn it off if you execute cron on your own. Automatic cron - is fake cron.
