### ISSUE TITLE
Email issues.

### ISSUE THREAD

**Issue by Worldwebdesign** [impresspages/ImpressPages#700]
Hi Guys,

Sorry to be a pain we have a new server and none of the forms are seding emails out now. We get the following error below. But we have checked the required ports and they are open. We have changed the email address here but the one we are using is valid and works and was working till me moved servers.

array(3) { ["to"]=> string(20) "mail@domain.com" ["subject"]=> string(20) "Website: Contact Us" ["body"]=> string(1024) "<h1 style="font-family: Trebuchet MS, Verdana, Tahoma; font-size: 28px; color: #00a8da;"> </h1> <p> <b>Name:</b> paul<br/> <b>Email:</b> mail@domain.com<br/> <b>Text:</b><br/> dlfjgldjfldjkfgjld<br/> </p> <p style="border-top: 1px dotted #7db113; height: 1px; font-size: 1px;"> </p> <p> Website <br/> <a href="mailto:testmail@domain.com">mail@domain.com</a> </p> <p> </p> <p style="text-align: right;"><span style="color: #6d6b70; font-family: Verdana, Tahoma, Arial; font-size: 10px;">Powered by </span><a style="text-decoration: underline; font-family: Verdana, Tahoma, Arial; font-size: 10px; color: #6d6b70;" href="http://impresspages.org">Impress Pages</a></p> " }

**Comment by maskas** [comment]
Please contact your hosting provider. ImpressPages has nothing to do with actual sending of an email when it is out of PHP control.

**Comment by Worldwebdesign** [comment]
We are using the smtp plugin. And the email account works as it has been tested. Anyway no worries I will solve it.
