### ISSUE TITLE
TinyMCE toolbar out of bounds

### ISSUE THREAD

**Issue by donnysim** [impresspages/ImpressPages#702]
Don't know if this is easy to fix, but when the content is close to the right edge (for example you have an ipSlot('text') in the headers top right corner. When you try to edit it, only ~half of the toolbar is visible as the other half is out of window bounds.

**Comment by maskas** [comment]
When youbuild your theme you know that. I suggest to do an exception and do a bigger space at the top so taht text tools would fit.

An alternative would be to modify tinymce config to appear bellow the text instead of above it.

**Comment by HalcyonD** [comment]
Vertical space is not a problem, its just that it doesn't stick to the right side of the window when there isn't enough space. 
![untitled](https://cloud.githubusercontent.com/assets/8076512/6374753/9f395180-bd1b-11e4-9b50-01ec9007e56e.png)

**Comment by maskas** [comment]
Ok. I was thinking the top is the problem. Nevertheless the solution probably is the same. Unless you think there is something we can add to the default TinyMCE config so that situations like these would be covered automatically.
