### ISSUE TITLE
cacheFix-parameter not passed to ipAddCss

### ISSUE THREAD

**Issue by mboehn** [impresspages/ImpressPages#704]
(Disclaimer: I'm no expert on OOP in PHP)
I'm trying to disable cacheFix (removing the "?1") for some CSS links.

Looking at the code, it seems that I need to send this with the ipAddCss-function:
```<?php ipAddCss('assets/theme.css', null, 50, false); ?>```
instead of
```<?php ipAddCss('assets/theme.css'); ?>```

This does however not work.
When looking at the classes, there seems to be a mismatch between what parameters the function expects and what it's being passed throughout the classes.

Ip/Internal/PageAssets.php
```public function addCss($file, $attributes = array(), $stage = 50, $cacheFix = true)```

Ip/Functions.php:
```function ipAddCss($file, $attribues = null, $stage = 50, $cacheFix = true)```
```\Ip\ServiceLocator::pageAssets()->addCss($absoluteUrl, $attributes, $priority);```

**Comment by maskas** [comment]
does this commit fixes the issue?
