### ISSUE TITLE
New user Needs help with Drip Pro Theme Banner

### ISSUE THREAD

**Issue by ossie59** [impresspages/ImpressPages#707]
Hello all I have installed Impress Pages ok and set up the database without too much trouble but I cannot seem to fine where I edit the hyper link on theDrip Pro main page banner which is labelled Title Block.  I can add a new link to the Title or the Text or the Read More Tab but do not know how to edit what looks like a hotspot.  If I hold my mouse on the hotspot and drag it I can see an address which is my domain name with /hash at the end.
Does anyone know how to edit the link.
Many thanks
Dave.

**Comment by maverikt** [comment]
Hi Dave,
Im not sure i entirely understand your question.  What do you mean by Drip Pro???  Do you have any screen shots?? Are you in admin or the user front end??
Tony

**Comment by ossie59** [comment]
i installed the impress pages then installed the Drip Pro theme which has an area i think its called the banner it has four blocks with four headings Title Block
![img_2198](https://cloud.githubusercontent.com/assets/11376117/6546119/920e0dda-c59e-11e4-9d49-6044b866e053.PNG)

**Comment by ossie59** [comment]
when you move the mouse over the hotspot it turns white with a hyper link that just stays on the sites main page I am trying to edit this link to go to a new page
![img_2199](https://cloud.githubusercontent.com/assets/11376117/6546139/3198db5a-c59f-11e4-9e9a-ec18ea179a1d.PNG)

**Comment by wannaco** [comment]
You should contact the theme author instead http://market.impresspages.org/author-profile/1005213
