### ISSUE TITLE
Question: Are plugins from static blocks ever removed?

### ISSUE THREAD

**Issue by arm1n** [impresspages/ImpressPages#709]
Hi there!

I've looked into IP's handling of removal of old revisions / widgets, cause one of my custom widgets uses `ipBindFile()` and `ipUnbindFile()` for handling repository files and I always get message in repository browser that the image is still in use on website, although it's actually deleted. After digging into the source I discovered the corresponding method in [Ip/Internal/Revision.php](https://github.com/impresspages/ImpressPages/blob/master/Ip/Internal/Revision.php#L172) and [Ip/Internal/Content/Model.php](https://github.com/impresspages/ImpressPages/blob/master/Ip/Internal/Content/Model.php#L585). If I've understood the code correctly, all widgets are dropped from DB if old page revisions are deleted and if WidgetController has implemented `delete()` it gets also invoked by this task. But I can't find any handling of static widgets, as they are persisted with `revisionId=0`? Am I missing something or is this intended behaviour? If yes, wouldn't this produce lot of database crap in the long run? Thank you for your input!

**Comment by maskas** [comment]
You are probably right. We should treat removed widgets in static blocks differently. I could even mark this as a bug. 

We have a setting if old revisions have to be deleted. We could use the same setting to decide if we need to delete old widgets from static blocks.

**Comment by arm1n** [comment]
Okay thank you for clarification! I agree that the same setting should be used for both static and dynamic widgets, but as static ones don't use actual revisionId, the only removal indictor would be `isDeleted` column from `ip_widgets` table, right? As there's also a timestamp for `isDeleted` column, it would even be possible to do the same time check for static widgets. Maybe Content's [Service](https://github.com/impresspages/ImpressPages/blob/master/Ip/Internal/Content/Service.php) and [Model](https://github.com/impresspages/ImpressPages/blob/master/Ip/Internal/Content/Model.php) need new methods to perform this task, which could be invoked by [removeOldRevisions()](https://github.com/impresspages/ImpressPages/blob/master/Ip/Internal/Revision.php#L172) after removal of dynamic widgets?

**Comment by maskas** [comment]
Exactly

**Comment by arm1n** [comment]
Great, let me know if I can help you or should prepare a pull request - don't know if you prefer to do such "hot topics" on your own or not ;)

**Comment by maskas** [comment]
Pull request would be great. I have a pile of tasks to do before this.

**Comment by arm1n** [comment]
Alright, I put it on my todo-list - hope I'll have some time left this week!

**Comment by maskas** [comment]
+1

**Comment by eazuka** [comment]
Hi @maskas, do i take it that this issue has been solved and its now part of the latest release of impresspages?

**Comment by maskas** [comment]
Yes. Thank You.
