### ISSUE TITLE
Error after installing new paid theme

### ISSUE THREAD

**Issue by DDACT** [impresspages/ImpressPages#714]
I've bought the theme Brightr, then uploaded it in the Theme folder via FTP and installed it in the admin section. But I get error codes in the log and an error code in the main screen:

file_put_contents(/home/ddactsk77/domains/ddact.nl/public_html/Theme/Brightr/assets/theme.css) [function.file-put-contents]: failed to open stream: Permission denied in /home/ddactsk77/domains/ddact.nl/public_html/Ip/Internal/Design/LessCompiler.php:195Cannot modify header information - headers already sent by (output started at /home/ddactsk77/domains/ddact.nl/public_html/Ip/Internal/ErrorHandler.php:62) in /home/ddactsk77/domains/ddact.nl/public_html/Ip/Response.php:221Cannot modify header information - headers already sent by (output started at /home/ddactsk77/domains/ddact.nl/public_html/Ip/Internal/ErrorHandler.php:62) in /home/ddactsk77/domains/ddact.nl/public_html/Ip/Response.php:221Cannot modify header information - headers already sent by (output started at /home/ddactsk77/domains/ddact.nl/public_html/Ip/Internal/ErrorHandler.php:62) in /home/ddactsk77/domains/ddact.nl/public_html/Ip/Response.php:227

Can anyone help me solve this please? What should I do? Thanks in advance!

**Comment by TheFOBas** [comment]
Make sure your theme directory is writable for ImpressPages to compile new css files.

**Comment by DDACT** [comment]
Thanks for your answer. But how do I do that?

**Comment by maskas** [comment]
there are many ways to do this. One of the ways is using FileZilla FTP client: http://www.dummies.com/how-to/content/how-to-change-file-permissions-using-filezilla-on-.html

It would be the best if you set write permissions for the whole Theme directory and all subdirectories and files. FileZilla has a checkbox to do this automatically.

**Comment by DDACT** [comment]
That worked! Thanks a lot!
