### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by demolaokesola** [impresspages/ImpressPages#717]
I have been using Impresspages for hopealivecc.org for several months now but recently I continually get this 500 Internal Server Error. Now I have an important update to make and it persists.

I really don't know what to do or how to fix this.

**Comment by wannaco** [comment]
I see your domain is hosted by sysKay Systems and they use Cpanel http://www.syskay.com/hosting.html

In Cpanel go to the Error Log reports and check what is being logged. 500 are mostly config, file permissions, etc.

**Comment by demolaokesola** [comment]
Unfortunately I can't even access the cPanel... same 500 Internal Server Error. <a href="www.hopealivecc.org/cpanel">hopealivecc.org/cpanel</a> is also inaccessible.

**Comment by wannaco** [comment]
You'd better contact their support and probaly start thinking about moving to a more reliable hosting.

**Comment by demolaokesola** [comment]
Ok Thanks. I have opened a support ticket.
