### ISSUE TITLE
url routing doestn work?

### ISSUE THREAD

**Issue by renickbuettner** [impresspages/ImpressPages#718]
i cant use url routing for all my impresspages installations...

**Comment by maskas** [comment]
Maybe you are using it incorrectly? Try out examples in our docs https://www.impresspages.org/docs/routing

Bu the way, have a look at this topic https://www.impresspages.org/docs/nice-urls

**Comment by renickbuettner** [comment]
At the moment nice urls work, but routing doestn work by plugins. i installed for testing the HelloWorldRouting Plugin from Impresspages and it doestn work.. :(

**Comment by maskas** [comment]
So after installing HelloWorldRouting plugin, the following URL doesn't work?

example.com/hellorouter/jon/smith

The voice is not perfect, but it could be extremely useful to watch https://www.youtube.com/watch?v=WFcseSOwpkE
