### ISSUE TITLE
Auto resizing text of "Heading" plugin

### ISSUE THREAD

**Issue by baksteris** [impresspages/ImpressPages#719]
Now text of Heading is not utoresizing, it is very actual for mobile devices. 
I suggest to do ressizitable text of Heading

**Comment by jankus** [comment]
If you're talking about Heading widget then everything depends on the Theme. Size is defined by the CSS. It doesn't relate with core functionality.

**Comment by baksteris** [comment]
OK, maybe possible include in setting of "Heading" widget possibilities select one of the text typing: default or with "text editor"?

**Comment by jankus** [comment]
What features do you need from text editor for Heading?

**Comment by baksteris** [comment]
I thought that with text editor can then text will be auto resizing. If not, then topic is locked :)

**Comment by jankus** [comment]
Auto-resizing can be made only through CSS with @media queries. Text editor can set only static size. Nothing dynamic. That's why you should depend on theme developer and not your "editor user" skills =]
