### ISSUE TITLE
SitemapXml Plungins always insert first language

### ISSUE THREAD

**Issue by thork123** [impresspages/ImpressPages#726]
<url>
<loc>http://example.com/tr/tr-title/</loc>    // this is right link and correct langulage tag
<lastmod>2015-05-50</lastmod>
</url>
<url>
<loc>http://example.com/tr/en-title/</loc>  //this is link is broken and wrong language tag

right one is <loc>http://example.com/en/en-title/</loc>

sitemapxml is mapping all of website inculde first and second langulage but second lang. link is broken

**Comment by maskas** [comment]
Thanks. Confirmed.

Comment Close and comment

**Comment by maskas** [comment]
I think this has been closed on the plugin repository https://github.com/impresspages-plugins/SitemapXml/issues/1
