### ISSUE TITLE
English language typo

### ISSUE THREAD

**Issue by severfire** [impresspages/ImpressPages#731]
"Bellow selected" -> "Below selected"

**Comment by maskas** [comment]
+1

 :)

**Comment by Twiggled** [comment]
That has been on since early this year when one of the early version 4's was released. lol

**Comment by bekoli** [comment]
I wonder how many native speakers use IP.

**Comment by Twiggled** [comment]
I have more than 60 Native English people using IP for there sites now and growing every day.
It has given them more control over there sites in an easier way which I love. Just need to fix the little things like this and the site urls which we have had issues as the URL's do not nest.

**Comment by bekoli** [comment]
Wow, that's a number. Thanks for feedback :+1:

**Comment by maskas** [comment]
Thanks. Fixed now.
