### ISSUE TITLE
2 or more layers popups   AND   removeClass("modal-open") 

### ISSUE THREAD

**Issue by ash0080** [impresspages/ImpressPages#736]
![2015-07-03 8 12 29](https://cloud.githubusercontent.com/assets/2803210/8498977/04bc0a26-21c0-11e5-8f4b-364d42084cf1.png)

For example,  an additional url selection popup like above

if you click the close in the url mode, the js will remove the "modal-open" on *Body*, 
the bg popup is still there but unscrollable.

quick and dirty fix:

/Ip/Internal/Core/assets/admin/bootstrap/bootstrap.js

Replace 
```
a.$body.removeClass("modal-open")
```
with
```
if(!$('.modal[aria-hidden=false]').length) {
a.$body.removeClass("modal-open");
};
```

Maybe there are better ways to do that, plz tell me if you know. 
cuz I think mod the bootstrap is not elegant...

Sorry, there has been a better solution [here],  plz close this post (https://github.com/HalcyonD/ImpressPages/commit/d17a7f714483751a004d9bdf6b1609085d09a448)

**Comment by maskas** [comment]
Thanks. Probably could be closed now :)
