### ISSUE TITLE
SendMail from Form doesn't work after upgrade to 4.6.2

### ISSUE THREAD

**Issue by HeinOpal** [impresspages/ImpressPages#740]
After I have upgrade my impresspages installation to 4.6.2 the sending of a form doesn't work any more. The mail is not sent and in the system log I find:

Time 	Message 	Context
2015-07-17 23:22:59 	Email.sendFailed: Heuweilermer Bürgerrunde: Home to tfrank@tfrank.net 	

array(3) { ["to"]=> string(17) "tfrank@tfrank.net" ["subject"]=> string(31) "Heuweilermer Bürgerrunde: Home" ["body"]=> string(1110) "<h1 style="font-family: Trebuchet MS, Verdana, Tahoma; font-size: 28px; color: #00a8da;"> </h1> <p> <b>Name:</b> HeinOpal<br/> <b>Email:</b> Hein@Opal.net<br/> <b>:</b> Bitte nehmen Sie mich auf den Mailverteiler<br/> </p> <p style="border-top: 1px dotted #7db113; height: 1px; font-size: 1px;"> </p> <p> Heuweilermer Bürgerrunde <br/> <a href="mailto:heuweilermer-buergerrunde-website@heuweiler.net">heuweilermer-buergerrunde-website@heuweiler.net</a> </p> <p> </p> <p style="text-align: right;"><span style="color: #6d6b70; font-family: Verdana, Tahoma, Arial; font-size: 10px;">Powered by </span><a style="text-decoration: underline; font-family: Verdana, Tahoma, Arial; font-size: 10px; color: #6d6b70;" href="http://www.impresspages.org">ImpressPages</a></p> " }

**Comment by maskas** [comment]
I doubt it could be related to the update to 4.6.2. Does the fresh installation of ImpressPages previous installation sends emails? Last time that part of ImpressPages was touched in version 4.5.2

**Comment by bekoli** [comment]
Hi HeinOpal,
your problem is probably deeper. Without further configuration the MTA from the system below is used. This is usually "sendmail". This fails on your server however. Is sendmail installed? If so make sure to check your logs.

I can help you debugging this if you're running Linux (won't touch others).

**Comment by HeinOpal** [comment]
Hi maskas an Hi bekoli,
thank you for your timely response. Your support is greatly appreciated.

Why do I think the problem is related to the upgrade?
I have two web sites on the same machine which I can only access via ftp. One is buergerrunde.heuweiler.net and the other is jugendabteilung.schinkelhuber.de. They both have the same kind of installation and I installed 4.6.1. on both. I added some themes and some plugins from Market to each of them, but not the same on both. After a while I upgraded buergerrunde.heuweiler.net to 4.6.2. I didn't check the sending functionality of the form widget since then but I tried it recently and buergerrunde.heuweiler.net didn't work anymore while jugendabteilung.heuweiler.net is still working fine.

So my suspect was that the difference in behaviour is related to a difference of the installation. And the only difference besides a differing set of themes and plugins is the version upgrade.

Any ideas how to troubleshoot?
Best Regards from southern Germany.

**Comment by HeinOpal** [comment]
![br](https://cloud.githubusercontent.com/assets/13386810/8761271/7e9e18aa-2d48-11e5-82d2-a6f145474156.jpg)
![ja](https://cloud.githubusercontent.com/assets/13386810/8761274/cd20f358-2d48-11e5-97a9-92faf1c98b34.JPG)

**Comment by maskas** [comment]
There was a bug in GIRD that GIRD didn't display any title if it is not set explicitly. That had been fixed and DB table name was used as the default title of the GRID if no title is defined. And that obviously resulted in this situation. The fix is easier as writing this comment here - just setting the title to the grid config. Nevertheless thanks for the discussion :)

**Comment by HeinOpal** [comment]
What do you mean with bug in GRID? The problem is not that there is nothing displayed in the Log Table View but that there is email sent:
![mailfail](https://cloud.githubusercontent.com/assets/13386810/8761321/e693b48a-2d4b-11e5-8221-f280c89cb55e.JPG)

**Comment by maskas** [comment]
Sorry guys, there was another bug that complained there is an incorrect titlel 'email_queue' instead of "Email queue".

**Comment by HeinOpal** [comment]
Ok, fine. So what do i have to do then?

**Comment by bekoli** [comment]
> I can only access via ftp.

So you're on a managed server? You've good chances that your operator broke the config.

Give me a call @HeinOpal . I'm way to lazy to write up what may go wrong with mailing. You find my phone number on maxr.org (a website of mine) in the Imprint. South germany'n stuff ;-)

**Comment by maskas** [comment]
@HeinOpal, as far as I know nobody else complain about broken email functionality. I would suggest to do a simple test by executing this PHP script on your server to see if your server can send emails at all:

http://www.w3schools.com/php/func_mail_mail.asp

**Comment by HeinOpal** [comment]
hi maskas, hi mekoli,

thank you for your help. After testing with the mailing functionality of php I was able to tackle the problem.
It was caused by a misconfiguration of php. My ISP has configured php that it can only run with a real mailbox as sender. I used a mail alias in one of the web sites and a mail box in the other.
Since i changed the configuration to a mail box instead every thing is fine.
Thank you an best regards from Freiburg

**Comment by bekoli** [comment]
Glad you found the issue @HeinOpal. Regards from Freudenstadt.

**Comment by machomaaan** [comment]
Hallo HeinOpal, hi Bekoli,

ich habe ebenfalls ein Problem mit dem Senden meiner Formulare.
Die Formulare werden zwar in den Email-Logs in IP gespeichert, aber in den "Error Logs" erscheint immer die Meldung dass die Email nicht gesendet werden konnte und ich erhalte das Fomular auch nicht per Email.
Laut meinen Provider fälscht mein Formular anscheinend den Absender.
Ich verwende das ganz normale Form-Widget und als Absenderadresse die System-Emailadresse.

Ich kann bei meinem Provider nur ein Postfach anlegen und diesem Postfach dann mehrere Alias-Adressen zuweisen. Es gibt aber keine Hauptadresse, welche dem Postfach fix zugewiesen ist, weshalb ich die Lösung von HeinOpal nicht anwenden kann.

Habt Ihr eine Idee?

Danke im Voraus.

**Comment by HeinOpal** [comment]
Hi Machoman,

 

sorry, ich kann dir damit nicht helfen. Bei mir löste sich das gesamte Problem auf, nachdem ich eine Mailbox verwendete.

Warum nimmst du nicht als Absender die Hauptadresse. Oder du wechselst im Zweifel halt den Provider.

 

Viele Grüße

HeinOpal

 

Von: machomaaan [mailto:notifications@github.com] 
Gesendet: Mittwoch, 27. Juli 2016 13:49
An: impresspages/ImpressPages
Cc: HeinOpal; Mention
Betreff: Re: [impresspages/ImpressPages] SendMail from Form doesn't work after upgrade to 4.6.2 (#740)

 

Hallo HeinOpal, hi Bekoli,

ich habe ebenfalls ein Problem mit dem Senden meiner Formulare.
Die Formulare werden zwar in den Email-Logs in IP gespeichert, aber in den "Error Logs" erscheint immer die Meldung dass die Email nicht gesendet werden konnte und ich erhalte das Fomular auch nicht per Email.
Laut meinen Provider fälscht mein Formular anscheinend den Absender.
Ich verwende das ganz normale Form-Widget und als Absenderadresse die System-Emailadresse.

Ich kann bei meinem Provider nur ein Postfach anlegen und diesem Postfach dann mehrere Alias-Adressen zuweisen. Es gibt aber keine Hauptadresse, welche dem Postfach fix zugewiesen ist, weshalb ich die Lösung von HeinOpal nicht anwenden kann.

Habt Ihr eine Idee?

Danke im Voraus.

**Comment by bekoli** [comment]
Man... totally missed that. I wonder whether Machoman found the problem :(

**Comment by idurar** [comment]
Hello, if someone looking to fix this problem (can't get mails ended from inform widget)here is solution : 

1- open your cpanel / pleks 
2- open phpMyadmin
3- go to your database  then open ip_email_queue table , then delete all data in this table
