### ISSUE TITLE
Publish and save drop down at top of menu time is not local

### ISSUE THREAD

**Issue by telitnow** [impresspages/ImpressPages#745]
Minor but helpful for the future.
Local UK based server at Zen internet.
The time is not local in the publish drop down at the top of the admin screen. Latest version of Impress Pages 4.6.3
phpinfo.php reports UTC under DATE but publish drop down shows 2:56 after save and publish when local time is 19:56
Would expect an hour different for British Summer Time but otherwise not what is shown. Does the locale need to be set in Impress? If so where?

**Comment by maskas** [comment]
It is probably related to the time zone setting in config.php. That value has been chosen during the installation. You can change it.

**Comment by telitnow** [comment]
Great thanks that fixed it.

**Comment by telitnow** [comment]
maskas
By the way really nice product. Keep up the great work. I'm sure there is lots more to do. Makes web editing really intuitive just as it should be.
Best Regards
JoG
