### ISSUE TITLE
Is it possible to edit classes and methods in \Ip\Internal\[...] other than view?

### ISSUE THREAD

**Issue by TechieKent** [impresspages/ImpressPages#749]
I tried using the override folder in Theme folder to replace php classes but to no avail. I would like to implement different logic to some core methods without editing ImpressPages core files.

Is there a way to do so?

**Comment by jankus** [comment]
Which methods you want to change? And what exactly to achieve?

**Comment by maskas** [comment]
ImpressPages uses autoloader. That means if you introduce a class before the Autoloader kicks in, your class will be used instead of the original. You can introduce your own implementations in index.php file. That won't affect updates.

**Comment by TechieKent** [comment]
Thanks for taking time to answer my question, jankus, maskas

I wanted to change a part of image upload method. Instead of keeping original file name, I want it to be renamed into something unique - such as `time()` - while keeping file extension.

I don't really understand the part on index.php, does it mean I can edit the index.php in ImpressPages' root folder, and updating ImpressPages will not have it overwritten?

**Comment by maskas** [comment]
Regarding file names in the repository. You really can't gracefully influence the file name of the repository. But you can catch a filter for all reflections of repository files (thumnails, etc.) and that can be done by catching the "ipRepositoryNewReflectionFileName" filter (https://www.impresspages.org/docs/filter-list).

In any case you can achieve your goals by modifying the index.php file in the root of installation. And yes, this file is not affected by the update.

**Comment by TechieKent** [comment]
I see. Look like editing core files is the way to go in my case. Thanks a lot ~
