### ISSUE TITLE
__() return publicLocale in admin pannel rather than adminLocale

### ISSUE THREAD

**Issue by chouex** [impresspages/ImpressPages#756]
adminLocale:en, publicLocale:zh_tw
![screen shot 2015-09-15 at 12 05 55](https://cloud.githubusercontent.com/assets/767140/9867704/4e574a20-5ba3-11e5-9965-2d64abb8fe82.png)

en language is exist
![screen shot 2015-09-15 at 12 09 12](https://cloud.githubusercontent.com/assets/767140/9867637/9b2cf1fc-5ba2-11e5-95ea-b039b6c8eb05.png)

before execure \Zend\I18n\Translator\Translator::translate 
the last setLocal call at Ip/Internal/Translations/Translator.php:55 [970edd5] 
it set local to zh_tw

**Comment by maskas** [comment]
Admin uses the same translation functions. It is just the namespace which makes the difference. Do you execute setLocale manually? Where is the actual issue? Translations function __ isn't working properly or admin view translations are mixed with public translations? Is that marked widget your custom widget?

**Comment by chouex** [comment]
not a bug.

i misunderstand admin and public translations is in the same file and language select by controller.

the file name should be *-admin-en.json for translations use in admin panel.
