### ISSUE TITLE
Ip\Form\Validator\Antispam seems to return error on forms, can't login to admin panel

### ISSUE THREAD

**Issue by severfire** [impresspages/ImpressPages#769]
just moved to new server,

```
if (!is_array($value) || count($value) != 2) {
       return $errorText;
}
```

count($value) seems to give back just 1. 

any ideas? :-/

**Comment by jankus** [comment]
For some reason your server automatically drops empty value. So if you can, check your server's configuration.

Antispam inserts two input fields - one empty, second with a hash - to trick bots. This blocks a lot of stupid spam. You server decides that you don't need empty post variable and drops it before it comes to PHP.

**Comment by maskas** [comment]
And if you find the reason, please report, so that we could make a proper decision if this needs to be handled differently on our side, or this is really weird server you have :)

**Comment by severfire** [comment]
can it be PHP handler? what would be the best?
now we are using Fast CGI

**Comment by maskas** [comment]
That could have some influence.
By the way can you answer yes to any of these questions?

Are you using nginx?
Do you run on Windows or Solaris?
Unusual PHP version?
Anything else unusual?

**Comment by severfire** [comment]
Linux, we are using Apache, we fixed issue by changing to CGI, I was playing with so many changes on rebuilds that I am unsure what finally fixed it. it is latest PHP 5.6.x
