### ISSUE TITLE
Major bug: Invalid default value for 'lockedAt'

### ISSUE THREAD

**Issue by XEuRoMAN** [impresspages/ImpressPages#777]
I can't install IP and error is showing completely unrelated error in view of true bug.

![error](https://cloud.githubusercontent.com/assets/3613663/13970212/01afa1ae-f090-11e5-9d25-f29d896bb223.png)

So, that thing confused me for some time but I noticed that there is missing a lot of tables in the DB...
Real problem is that `ip_email_queue` table is using wrong default value for `lockedAt` field.

![mysql_error](https://cloud.githubusercontent.com/assets/3613663/13970302/91b4aa06-f090-11e5-8bd3-f9110302e4b3.png)

According to the MySQL documentation: http://dev.mysql.com/doc/refman/5.7/en/datetime.html
valid range for `timestamp` is between
> '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC

I'm using latest MySQL 5.7.9 (on Windows 10), so maybe in previous versions it was warning or something but now it's error which is blocking table creation process (and that error is not showing in the IP).

I'm not doing pull request with the fix of this bug because maybe there is other stuff about `ip_email_queue` table which is related with current default value.

**Comment by maskas** [comment]
I guess it would be the best to change that field from "not null" to "null" with default value "null".
