### ISSUE TITLE
500 and 503 Errors

### ISSUE THREAD

**Issue by machomaaan** [impresspages/ImpressPages#780]
Hi.

I sporadically get 500 and 503 errors. I've tried to disable the cronjob or run cronjob by server directly...
My hostingprovider didn't see any PHP Errors.

Where does those Errors come from?

I've 3 websites - all of them have this problem.
New install, simply own theme...

Any ideas?

Thank you very much.

**Comment by wannaco** [comment]
check your server, and refer to the http codes https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by wannaco** [comment]
check your server, and refer to the http codes https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by machomaaan** [comment]
I've talk to my provider but they didn't find any issues and logfile is also empty?!?

**Comment by machomaaan** [comment]
No ideas? :(

**Comment by maskas** [comment]
According to the physics, there is one of these:

- either the error is not present
- server logging is off
- error appears in the log

you choose which one is a lie. I would try to specifically make an error in the code and see if it appears in server logs. If no, then you have an issue with the configuration of the server.
