### ISSUE TITLE
bug in ipFormatDateTime()

### ISSUE THREAD

**Issue by arsiesis** [impresspages/ImpressPages#781]
When i use ipFormatDateTime()

[https://www.impresspages.org/docs/ipformatdatetime](url)

if i give  a string for $languageCode

`<?php echo esc(ipFormatDateTime(strtotime($order['createdAt']), 'PayPal','fr_FR')) ?>`

i have a error because $code does'nt exist

in file : 
ImpressPages/Ip/Internal/FormatHelper.php >>>   227

i have add this :   

``
$code = $languageCode;

for debug... and now all work fine.

bye

**Comment by maskas** [comment]
Thanks. Will include the fix.
