### ISSUE TITLE
HTTPS issue when accessing market

### ISSUE THREAD

**Issue by severfire** [impresspages/ImpressPages#783]
js console: `Mixed Content: The page at 'https://site/?aa=RepositoryManager' was loaded over HTTPS, but requested an insecure resource 'http://market.impresspages.org/images-v1/?xdm_e=https%3A%2F%2Faddress.io&xdm_c=default3228&xdm_p=1'. This request has been blocked; the content must be served over HTTPS.`

**Comment by maskas** [comment]
Chrome doesn't like the way we have implemented the marketplace. But it must work. As long as it works, you shouldn't be concerned about that error/warning.

**Comment by severfire** [comment]
Nothing shows up as content is blocked. The store doesn't work with HTTPS.

**Comment by maskas** [comment]
You can apply these fixes to your ImpressPages installation or add the following line to config.php file:

'pluginMarketUrl' => 'https://market.impresspages.org/plugins-v1/?version=4&cms=1'

**Comment by severfire** [comment]
> plugin_market.js?40:58Uncaught SecurityError: Blocked a frame with origin "https://market.impresspages.org" from accessing a frame with origin "https://mobilution.io". Protocols, domains, and ports must match.

seems like in long run would be good doing that through API

a.

**Comment by maskas** [comment]
I regret the technology used behind the communication between the website and the server. API would work mutch better. But it is as it is for now.

I'm getting that error as well. EasyXDM library used in the market should do the job even when that error appears and it does work for me with these changes https://github.com/impresspages/ImpressPages/commit/ed18158e9ce10f72e468d2ec4cddbcf79e782957

Are you sure you have replicated all those changes identically?

**Comment by 4eburashk** [comment]
Сделайте внятную документацию хотябы по использованию http https // непонятно что писать в config.php
