### ISSUE TITLE
issues with using forms on phones.

### ISSUE THREAD

**Issue by severfire** [impresspages/ImpressPages#794]
Hello,

There are issues with using forms on phones.

IP version: 4.6.5
Phones: Galaxy S6, and iPhones (we don't know client's versions). 

my Sony works fine.

The problem is we cannot login to admin using phone, 
nor the other submit buttons work on other forms...

After I disabled the spamcheck and Csrf using 'return false;' at the beginning

It just refreshes the same page where the form is...

Any ideas?

**Comment by mrx** [comment]
Are you loading any other javascript for stats, click tracking, etc. ?

**Comment by severfire** [comment]
nothing, i installed fresh installation of impress pages for that, without any additional plugins :-/

**Comment by severfire** [comment]
the funny thing is that after i disabled the spamcheck and csrf i see in logs that user logged in: `Admin.loggedIn: root from xx.xx.xx.xx	array(2) { ["username"]=> string(4) "root" ["ip"]=> string(13) "xx.xx.xx.xx" }` but the site just refreshes to login page...

**Comment by mrx** [comment]
What browser are you using?

**Comment by severfire** [comment]
Chrome 51.0.2704.81, Android 5.1.1 D5503 build -- works
Chrome 51.02704.81;  Android 6.0.1 MMB29k build -- doesn't work

**Comment by severfire** [comment]
Impress Pages should work on all new devices and Browsers... :-/ seems like there some problems

**Comment by mrx** [comment]
Verify the browser is set to accept cookies and the session is being saved.

**Comment by severfire** [comment]
Ha, mrx, I didn't thought it may be cookies -- my friend disabled them some time ago and forgot about them... some of our customers may also have them disabled. I will do a fork and add option that says cookies are disabled, please enable them. thanks!!
