### ISSUE TITLE
Unreachable code in RepositoryFile grid field

### ISSUE THREAD

**Issue by XEuRoMAN** [impresspages/ImpressPages#796]
I'm making plugin of my custom field and noticed that there is some unreachable code in CMS core.

https://github.com/impresspages/ImpressPages/blob/ea121628e03f2a3b0d5764ac1c74427a65422197/Ip/Internal/Grid/Model/Field/RepositoryFile.php#L77

every code is in `isset` closure but inside this closure someone expecting that this value won't be `set`.
https://github.com/impresspages/ImpressPages/blob/ea121628e03f2a3b0d5764ac1c74427a65422197/Ip/Internal/Grid/Model/Field/RepositoryFile.php#L79
https://github.com/impresspages/ImpressPages/blob/ea121628e03f2a3b0d5764ac1c74427a65422197/Ip/Internal/Grid/Model/Field/RepositoryFile.php#L85

**Comment by maskas** [comment]
Cool?

**Comment by XEuRoMAN** [comment]
Cool.
