### ISSUE TITLE
Don't get form by email

### ISSUE THREAD

**Issue by machomaaan** [impresspages/ImpressPages#799]
Hi.

I don't receive form by email.
In Admin -> System -> Email Log i see all emails, but not on my mailbox.

If i fill out form with my own emailaddress, I receive the mail, but if somebody else fill out the form with his own emailaddress, I don't receive the form by email.

My provider told me that there is a false "from:" parameter?!?

Can anybody help me?

Latest ImpressPages version!

Thank you very much!

**Comment by jankus** [comment]
By default ImpressPages translates email in the form as "sender" and adds to "from" field for you to be able to click "Reply".

You can start with SMTPConfig plugin (https://market.impresspages.org/plugins/SMTPConfig) and update required field as you see appropriate before actual email goes out.

**Comment by machomaaan** [comment]
Great jankus!

That solved my problem! Thank you!
