### ISSUE TITLE
Lazy loading for image browser (ipsBrowser)

### ISSUE THREAD

**Issue by computerfreak84** [impresspages/ImpressPages#800]
Hello ip-Team

This is a suggestion for a future ImpressPages version:

**Would it be possible to have the image browser (ipsBrowser) load only a certain amount of recently uploaded images?**

The technique I would prefer is known as "lazy loading", but even some kind of "load older pictures"-button or similar would enhance the user experience.

**Reason for request:** I have a customer website with a lot of images and the more pics that are getting uploaded, the longer it takes before the image browser shows any of them, while mostly they just want to use some of the recently uploaded ones...

Thanks for looking into it.

**Comment by maskas** [comment]
+1

**Comment by azanov** [comment]
I implemented this feature for one of my customers recently. I only load the thumbnails of the images currently visible on screen. Additional thumbnails are loaded once the user is scrolling the page or resizing the window.

I'll prepare a pull request if this feature isn't part of the newest development release yet.

**Comment by eazuka** [comment]
Nice idea

**Comment by azanov** [comment]
@eazuka @maskas The issue can be closed, since the feature is already merged & available to everyone

**Comment by eazuka** [comment]
good, thanks @jankus

**Comment by computerfreak84** [comment]
As the original author of this issue, I wouldn't consider this issue solved at all.

You might have made it better, but it's nowhere near as I imagined it should be...

Especially in Firefox the current version of ipsBrowser doesn't almost work at all and get's my Firefox to not respond anymore for a minute or more.

In Chrome it works, but it still seems to load thousands of pictures, even though it should just load the latest 20 or so...

**Comment by azanov** [comment]
Have you tried the version that's available for download on the official website or the one on Github? There has been a patch for this issue later, which was not released yet. 

It deals with a bug with the position check of the elements. 

Also, the freeze at the beginning is due to the original request which fetches information about all images as JSON. This takes time. What I fixed is the loading of the images itself, not the initial request.

**Comment by computerfreak84** [comment]
@azanov I'm just using the latest official IP 5.0.3

So it sounds that someone should change the original request to only load a certain amount of pictures info as JSON...

Anyway, it's not the most important thing in the world, basically it's just a bit stupid that my clients upload pictures that are huge and seem to be unable to reduce them in pixel an kb size...

Any idea on how to implement some system that resizes all pictures?

**Comment by TheFOBas** [comment]
@computerfreak84  ImpressPages stores original images, but they are almost never used in original size. IP  will resize them to something smaller like thumbnail.
More info here: https://www.impresspages.org/docs/repository

**Comment by computerfreak84** [comment]
@TheFOBas: Thanks for your reply. I know about the capabilities of the repository.

Unfortunately when my client places images (ipWidget-Image) and uses the colorbox/Lightbox feature, the image is still used in full size, which I consider a major flaw.

Concerning the Repository I might make a screen recording to show you all the excessiveness of the issue in a case where there are hundreds if not thousands of really large JPGs...

I might sound unhappy, however I like to use this opportunity to thank all you contributors and devs for iP. Even after years I haven't found anything better or easier to use for my small client base. I hope it get's developed further on.

**Comment by TheFOBas** [comment]
@computerfreak84 Full size image in lightbox sounds like a bug and I think deserves separate Issue.

**Comment by computerfreak84** [comment]
@TheFOBas : Thanks for opening issue #887 - it's exactly the problem I described above.
