### ISSUE TITLE
Searching for small order-system

### ISSUE THREAD

**Issue by machomaaan** [impresspages/ImpressPages#802]
Hi.

I'm searching for a small order-system on ImpressPages.

I want to create 3-4 categories and add some articles.

Articles only have:
1x product image
1x product title
1x product description
1x product infosheet (.pdf) to download it

All products in the same category should be displayed on one page like:

**************************************************************************************
Operating Systems
---------------------
ImageXP       Windows XP                           Items: __ pcs.
                     Description here...
                     Infosheet WinXP.pdf

ImageW7     Windows 7                              Items: __ pcs.
                     Description here...
                     Infosheet Win7.pdf
**************************************************************************************

I would to add one or more items onto a list (like a small cart) for overview, enter name and contacts (form) and send it.

Can anybody help me? I would pay for this plugin if needed.

Thanks alot!

**Comment by mrx** [comment]
I can write the plugin for you but you'll need someone else to provide design / artwork for your website. 

john at nitro.pro

**Comment by machomaaan** [comment]
Hi.

The design for my website is no problem.
Can i use this plugin like a widget or hardcoded?

How much is it ;)

**Comment by machomaaan** [comment]
Sorry...I use "close and comment" instead of "comment" :)

**Comment by mrx** [comment]
I'm not sure of your full requirements but I think this can be done with a grid control to manage the back-end, a few routes to list inventory by category and two or three view files. 

If your OK with donating the plugin back to the community, I'll help you for free. 

We should move this off of github so we aren't annoying people following actual issues. Contact me by email: john at nitro.pro

**Comment by machomaaan** [comment]
I'll send you an email ;)
