### ISSUE TITLE
AdvancedGoogleMaps. api key google map

### ISSUE THREAD

**Issue by neimp** [impresspages/ImpressPages#805]
Hi
 Now Google forces each website to provide a unique Google Maps API key  for maps to work. Otherwise instead of the map you'll see an error message.
 How I can resolve this problem for the plugin AdvancedGoogleMaps. because it does not appeal to the google api
Thanks by advance

**Comment by maskas** [comment]
Update to 4.7.0 and entering the API key must solve the issue https://www.impresspages.org/impresspages-4-7-0

**Comment by neimp** [comment]
Hello
Thank you for your reply.
I have the latest version of impresspages.
I put the api key google map but the **plugin AvancesGoogleMap** does not work because it **does not appeal to the API key** and google block
At another site , it works because having been a key api before June 2016 and Google accepts for sites created before June 2016
Thanks by advance
Best Regards
André

**Comment by maskas** [comment]
This plugin is made by the community. You probably will have to tweak it to make it work.
