### ISSUE TITLE
How to create a plugin/widget that insert simple placeholders?

### ISSUE THREAD

**Issue by machomaaan** [impresspages/ImpressPages#808]
Hi.

How can i create a plugin/widget that insert placeholders for image and text by drag and drop do the right place on site?

The widget should like:
`<div class="product>
   <h2>Producttitle</h2>
   <div class="productimage">PLACEHOLDER: for image (select image or drag&drop imagewidget)</div>
   <div class="productdescription>
      <h2>PLACEHOLDER: Producttitle</h2>
      <p>PLACEHOLDER: Description goes here...</p>
      <div class="productdownload>PLACEHOLDER: Datasheet (select file to download)</div>
   </div>
</div>`

I want to insert the widget multiple times on a site (like a productlist).
How can i do this?

Thank you very much.

**Comment by jankus** [comment]
You can check a few plugins for an inspiration or straight usage:

1. https://market.impresspages.org/plugins/GridWidget
1. https://market.impresspages.org/plugins/CustomSection

**Comment by machomaaan** [comment]
Hi Jankus,

thank you. I've tried GridWidget and create this (AdminController.php):

`<?php
/**
 *
 */

namespace Plugin\GridExample;


class AdminController extends \Ip\GridController
{
    protected  function config(){
        return array(
            'title' => 'Products',
            'table' => 'gridExample',
            'deleteWarning' => 'Are you sure?',
            'sortField' => 'personOrder',
            'createPosition' => 'top',
            'pageSize' => 5,
            'fields' => array(
				array(
                   'type' => 'Select',
                   'label' => 'Category',
                   'field' => 'Category',
                   'values' => array(
                       array('black', 'black'),
                       array('blue', 'blue'),
					   array('red', 'red'),
					   array('withe', 'withe')
                   )
                ),
                array(
                    'label' => 'Productname',
                    'field' => 'Productname'
                ),
				array(
					'type' => 'Textarea',
                    'label' => 'Decription',
                    'field' => 'Decription'
                ),
				array(
                    'type' => 'RepositoryFile',
                    'label' => 'Productimage',
                    'showInList' => true,
                    'field' => 'Productimage'
                ),
                array(
                    'type' => 'RepositoryFile',
                    'label' => 'Datasheet',
                    'showInList' => true,
                    'field' => 'Datasheet'
                ),
				array(
                    'type' => 'Checkbox',
                    'label' => 'Aktiv',
                    'showInList' => true,
                    'field' => 'Aktiv'
                )

            )
        );
    }

}`

And this is the Worker.php:
`<?php

//namespace Plugin\GridExample\Setup;
namespace Plugin\GridExample\Setup;

class Worker extends \Ip\SetupWorker
{

    public function activate()
    {
        $sql = '
        CREATE TABLE IF NOT EXISTS
           ' . ipTable('gridExample') . '
        (
        `id` int(11) NOT NULL AUTO_INCREMENT,
        `personOrder` double,
		`Category` varchar(255),
        `Productname` varchar(255),
        `Decription` varchar(255),
		`Productimage` varchar(255)
		`Datasheet` varchar(255)
        `Enabled` boolean,
        PRIMARY KEY (`id`)
        )';

        ipDb()->execute($sql);

    }

    public function deactivate()
    {

    }

    public function remove()
    {

    }

}
`

But this doesn't work (fatal error... if I wan't to save a product)

And I don't know how to show the data in frontend?!?

Thanks alot for help.

**Comment by machomaaan** [comment]
Oh sorry, there is something going wrong with the "insert code" function...

oh by the way...
I'd like to display the insert data in "**GridExample**" in frontend into seperate categories (menu).

So I want to add "Black" to menu and then all products of categorie black should be displayed.

Thanks.
