### ISSUE TITLE
Sessions never expire

### ISSUE THREAD

**Issue by maskas** [impresspages/ImpressPages#820]
Reproduce:
- login to admin
- close the browser
- open the browser in 3h and watch admin panel

**Comment by bekoli** [comment]
7979cf2febcd4bb02b0c3a913eb3bb598ce42ea3 suggests 30 (hardcoded) minutes. Way to short for my taste. This should be configureable or last an extended coffee break, shouldn't it?

**Comment by eazuka** [comment]
you can change it to your desired duration. please read this blog post https://www.impresspages.org/impresspages-4-9-0

**Comment by bekoli** [comment]
Thanks for the heads up @eazuka
