### ISSUE TITLE
HTML Editor (Pop up) Grayed out

### ISSUE THREAD

**Issue by DGIANZ** [impresspages/ImpressPages#844]
Hey guys! I am developing a theme and when I try to drag and drop a HTML widget, the pop up editor is grayed out. On the included themes, Air and QuickStart, the editor works fine. I have provided a screenshot.

![image](https://cloud.githubusercontent.com/assets/13766009/25353274/aa248872-28fc-11e7-881e-0a6f478bdf10.png)

**Comment by wannaco** [comment]
Are you using bootstrap and loading its resources in the admin panel?  https://www.impresspages.org/docs/javascript

**Comment by DGIANZ** [comment]
Thank you, wannaco for responding! I appreciate you taking the time to help me. :)

I am using the bootstrap.min.css file, but not the .js file. I am willing to provide my theme files if necessary.

This is a sample of my header.php file 
`<?php echo ipDoctypeDeclaration(); ?>
<html<?php echo ipHtmlAttributes(); ?>>
<head>
    <?php
        ipAddCss('Ip/Internal/Core/assets/ipContent/ipContent.css'); // include default CSS for widgets
        ipAddCss('assets/style.css');
        ipAddCss('assets/css/colors/default.css');
        ipAddCss('assets/css/bootstrap.css');
        ipAddCss('assets/fonts/font-awesome/css/font-awesome.min.css');
        ipAddCss('assets/css/menus.css');
        ipAddCss('assets/css/animate.min.css');
        ipAddCss('assets/css/form.css');
        ipAddCss('assets/css/owl.carousel.css');
        ipAddCss('assets/css/typography.css');
        echo ipHead();
    ?>
    <link rel="stylesheet" id="specia-fonts-css" href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C400%2C600%2C700%2C800%7CRaleway%3A400%2C700&amp;subset=latin%2Clatin-ext" type="text/css" media="all">
</head>`

Here is a sample of my footer.php file.
`</div>
<?php
    ipAddJs('assets/theme.js');
    echo ipJs();
?>
</body>
</html>
`

I do have a main.php file and can provide the code of that as well.

I would like to thank anyone that takes the time to respond to this post.

**Comment by maverikt** [comment]
Hi,
Please try this:

Open main.less in the theme asset folder. add z-index: 1051; to the .ip .modal-dialog class. You should end up with something like:
.ip .modal-dialog {
    width: 800px;
    z-index: 1051;
}
This should fix the bug.

If your not using less then just add this to one of you css files.

Tony

**Comment by DGIANZ** [comment]
Maverikt, your solution has worked. Thank you very much! Thank you to all who took the time to respond to this issue. I will now close it.
