### ISSUE TITLE
Getting started with ImpressPages from Github

### ISSUE THREAD

**Issue by Remo** [impresspages/ImpressPages#845]
I've installed the official download and quickly found a few warnings I thought I could easily fix. It turns out it's not that easy as the github version doesn't install that easily.

I've installed the composer dependencies and started a webserver in `start-pack`. That fails with `Cannot find relative path` for `ImpressPages/Ip/Internal/Install/Helper.php`. Okay, seems like a missing file is causing a problem, let's try the install script.

I switch into `bin` and run the script, can't find `autoload.php`, I go a level higher, still can't find it. I look into the code and wonder how that can even work, there's no `vendor` in the path. I change the path, next try, fails because the script should be executed from the project root where composer.json is placed, that's where I am...

I believe I've skimmed through all pages in your documentation and can't find a single word about this. The readme in this repo is also very short and doesn't contain anything that would help me.

Please tell where I should have looked for the missing instructions and please add/link them to the readme!

**Comment by maskas** [comment]
Have you executed 'composer install'?

**Comment by Remo** [comment]
Yes, I've installed the composer dependencies, but how should this code ever work if it's supposed to be executed in the root directory https://github.com/impresspages/ImpressPages/blob/master/bin/setup.php#L3?

**Comment by maskas** [comment]
Please read "try" section:

https://www.impresspages.org/impresspages-5-preview

**Comment by Remo** [comment]
That's it, thanks! Works fine!
