### ISSUE TITLE
Parse error: syntax error, unexpected 'array' (T_ARRAY) ...../Ip/Form/Field/Color.php 

### ISSUE THREAD

**Issue by myke4416** [impresspages/ImpressPages#852]
There is an error in the current Color.php file.  For any theme I would try and edit - I would receive: Parse error: syntax error, unexpected 'array' (T_ARRAY) in /my/site/path/Ip/Form/Field/Color.php on line 51  The array is repeated several times in the file.  To correct the problem, edit the file, deleting the repeated array statements.  This has been driving me nuts as I am not much of a programmer... but this does affect everyone using IP 5.0.2!  

BTW - ImpressPages is EXCELLENT software and has saved me many hours of web development time!!! THANK YOU!!!!

**Comment by maskas** [comment]
I guess here is the fix https://github.com/impresspages/ImpressPages/pull/850
