### ISSUE TITLE
Installation Problem "Unexpected Error"

### ISSUE THREAD

**Issue by HeinOpal** [impresspages/ImpressPages#855]
Hi ImpressPages,
I am currently struggeling to install ImpressPages 5.02. I use PHP 5.6.30.
Starting the installation process seems to work fine
![grafik](https://user-images.githubusercontent.com/13386810/27482035-f9e1d912-581f-11e7-9db5-44c031db9bf4.png)
After hitting Next I get "Unexpected Error"
![grafik](https://user-images.githubusercontent.com/13386810/27482150-7f73a75e-5820-11e7-9c23-bbc0b2f75337.png)

Where can I see what the problem is?
Thanks in advance
Thomas

**Comment by maskas** [comment]
Hello,

you are not the only one getting it. But nobody had a look at the exact reason. Please open debug console in the browser and look for 500 requests in network tab.

**Comment by maskas** [comment]
And here I have reproduced it while testing the new 5.0.3 release! Looking what and why is happening there.

**Comment by maskas** [comment]
And removing config.php file and going again to the root of the website fixes the issue. Digging deeper.

**Comment by HeinOpal** [comment]
Thank you maskas for your support. Removing/Renaming the config.php solved my problem.

All the best from southern Germany
Thomas

**Comment by jankus** [comment]
From my tests it was some server configuration that forces redirect during AJAX call with post data. Then request get error and returns contents of redirected page. That's why response is so weird. But it doesn't happen for everyone.
