### ISSUE TITLE
Rebuild management.min.js

### ISSUE THREAD

**Issue by azanov** [impresspages/ImpressPages#857]
Hi,

I am currently testing some extensions for the Gallary Widget and would like to rebuild the minified `management.min.js` file ([imported here](https://github.com/impresspages/ImpressPages/blob/1d0dd34e9a4de702d75bed1d8d9aa562d90462d7/Ip/Internal/Content/Helper.php#L78)).

I could not find any way within the framework code to rebuild it automatically. When I look at the contents, it looks like a simple concatenation to me. Can you publish the script you use to build it?

**Comment by maskas** [comment]
We have a plugin to do this job:

https://github.com/impresspages-plugins/CoreCompiler

When you have this plugin activated, it recompiled minified js on pageload.

**Comment by azanov** [comment]
Great, thank you!
