### ISSUE TITLE
Set Config.tmpFileExistance

### ISSUE THREAD

**Issue by koos91** [impresspages/ImpressPages#858]
I was searching how often the "files/tmp" directory is being cleaned, I want it more often.

Now I found that inside the "Internal/Core/Event.php" file there is a function (ipCronExecute) thats calls another function (cleanDirRecursive) wich delete the content from "tmp". But inside the "cleanDirRecursive" function there is a variable "Config.tmpFileExistance". The problem is I can't find where this variable is set, and how to change it's value.

**Comment by azanov** [comment]
The options readable by `ipGetOption` are stored in the database, have a look at the `ip_storage` table. By default, there is no value stored for the option `Config.tmpFileExistance` and the default value from the `ipGetOption` call is taken (`14`)

**Comment by koos91** [comment]
I already looked in the `ip_storage` table and indeed did not found the `config.tmpFileExistance` so than came up the question why isn't it in the database (and editable trough the cms), and if I add it manualy will it not be overwritten (removed) when there is an update of ImpressPages?

**Comment by jankus** [comment]
In ImpressPages we took a strategy to put all variables in `ipGetOption()` format to allow anyone to change defaults at any time. There's no point to duplicate defaults in code and do the same in DB.

At the same time we are thinking about less knowledgeable users who can mess up their own websites without knowing it. The end result is that you can change pretty much anything but we don't provide a default interface for that. If you really need to have an interface for that, you can quickly build your own custom plugin with simple form and update any option as you need. In other cases, if you are not happy with defaults, it means to are a tech-savvy enough to add extra parameter into the database according to your needs. And you are really aware of what you are doing.

ImpressPages update mechanism changes only files and very rarely some data structures in DB. None of the data is touched, cleaned or somehow altered (only structure and ir rare cases location). We have no right to change your own work.

**Comment by koos91** [comment]
Thanks @jankus I have added the parameter in the database manualy, now I know the DB will not being changed while updating it will not be a problem.
