### ISSUE TITLE
Z-index ipAdminNavbar and ipsAdminPanel to low

### ISSUE THREAD

**Issue by koos91** [impresspages/ImpressPages#859]
As you can see in the screenshot below the z-index of the header/menu of IP is having a lower z-index then the widget-controlbar.

![screenshot_1](https://user-images.githubusercontent.com/19344487/28755730-a715524a-7561-11e7-8ee5-6bffe8c12070.png)

I think it is a good idea to change these z-indexes in IP core in upcoming versions. Agree?

**Comment by jankus** [comment]
If navbar z-index is bigger then you won't see text controls and you'll think widget doesn't work.

**Comment by koos91** [comment]
Yes, that's true. It is irritating me but indeed other people may think the widget is not working.

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
