### ISSUE TITLE
Lost admin interface

### ISSUE THREAD

**Issue by SOMRC** [impresspages/ImpressPages#863]
Hi, I've suddenly lost the admin interface for a website I look after (spiritofmonmouth.co.uk)

Using the same login details I've used successfully for months, it now says "page not found" and no admin options appear.

This stopped working on Chrome about a week ago, then stopped working on IE too a few days later - so it makes me think it's not my login details to blame.

Any suggestions much appreciated please!!

**Comment by jankus** [comment]
Maybe server configuration has changed? Try a full path to a admin.php file, i.e. http://spiritofmonmouth.co.uk/admin.php

However, when I go to "www" version, your website redirects to a "Impress" subfolder. And admin page loads normally - http://spiritofmonmouth.co.uk/Impress/admin

**Comment by SOMRC** [comment]
That second link has worked for me too, thank you so much jankus!
