### ISSUE TITLE
Impress site broke after host's PHP7 upgrade

### ISSUE THREAD

**Issue by SOMRC** [impresspages/ImpressPages#864]
Hi, 

I look after a website which has Impress CMS with UK2 hosting. Recently, UK2 did an upgrade which brought down the website, this was the error:

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/spirito4/public_html/Impress/ip_cms/includes/db.php:24 Stack trace: #0 /home/spirito4/public_html/Impress/ip_cms/frontend/init.php(14): Db::connect() #1 /home/spirito4/public_html/index.php(49): require_once('/home/spirito4/...') #2 {main} thrown in /home/spirito4/public_html/Impress/ip_cms/includes/db.php on line 24

This was their response to my support ticket:

"Ok so the problem occurred because of the recent php 7 upgrade. Which was mostly a
security update, but also affects many plugins and themes as well. This means a lot of your website is now outdated. I have reverted it back for you so that you can update all of your plugins, themes, wordpress, etc. You will need to have all of these updates done by Monday, November 6th, because at that point the older version of php will be deleted from our servers."

I've looked at every option on the Impress admin interface and have NO idea how to update the Impress CMS such that it won't break again on November 6th.

Does anyone have any suggestions please??

**Comment by jankus** [comment]
You are using a very very old version of ImpressPages. There's no magic button to upgrade it automatically. The only option to support PHP7 is to rebuild website with newest ImpressPages version.

By the way, PHP7 is not "mostly a security update". It's a new major version after PHP5.6. New major version drops a lot of features and that requires to rebuilt software.

**Comment by SOMRC** [comment]
eeek! Ok, thank you Jankus!
