### ISSUE TITLE
error after installing DataTable Widget

### ISSUE THREAD

**Issue by PonaciousPioneer** [impresspages/ImpressPages#865]
I have a new install of ImpressPages at JohnBenaiah.com/IP/ and after installing the plugin DataTable Widget I encountered the following error.  I opened cpanel on the site, deleted the DataTable Widget folder and the error cleared allowing access to the IP site again.
/JF
---
Fatal error: Uncaught Ip\Exception: ipFile function accepts only paths, that start with Ip/, Plugin/, Theme/, file/. Requested path: /home/johnbenaiah/public_html/IP/Plugin/DataTableWidget/Widget/DataTable/assets/plugins in /home/johnbenaiah/public_html/IP/Ip/Functions.php:531 Stack trace: #0 /home/johnbenaiah/public_html/IP/Ip/Internal/Content/Event.php(18): ipFile('/home/johnbenai...') #1 /home/johnbenaiah/public_html/IP/Ip/Internal/Content/Event.php(27): Ip\Internal\Content\Event::includeResources('/home/johnbenai...') #2 /home/johnbenaiah/public_html/IP/Ip/Internal/Content/Event.php(12): Ip\Internal\Content\Event::includeResources('Plugin/DataTabl...') #3 /home/johnbenaiah/public_html/IP/Ip/Internal/Content/Event.php(56): Ip\Internal\Content\Event::addWidgetAssets(Object(Plugin\DataTableWidget\Widget\DataTable\Controller)) #4 [internal function]: Ip\Internal\Content\Event::ipBeforeController(Array) #5 /home/johnbenaiah/public_html/IP/Ip/Internal/Dispatcher/EventDispatcher.php(38): call_user_func('\\Ip\\Internal\\Co... in /home/johnbenaiah/public_html/IP/Ip/Functions.php on line 531

**Comment by jankus** [comment]
This plugin is not compatible with ImpressPages v5.x

**Comment by PonaciousPioneer** [comment]
Thanks. A note about that would be helpful in  the list of plugins for first timers like me. /JF
