### ISSUE TITLE
Installation failure: file extension missing

### ISSUE THREAD

**Issue by takugoishii** [impresspages/ImpressPages#866]
Hi, 

I encountered a trouble in the early stage of ImpressPages 5.0.3 installation. After entering the database information, the automatically selected URL is <ImpressPages home>/admin, in which the file extension “.php” should be lacking because the actually existing file in the directory <ImpressPages home> is admin.php. Accessing to <ImpressPages home>/admin.php is possible, but the login ID is lacking, displaying only the password. If I hit the “Ok” button, the following unexpected error appears: 

```
Unexpected error.<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /ImpressPages/admin was not found on this server.</p>
</body></html>

```

It seems that something is wrong with URL generation. Is there anybody who can tell me what to do or what to check to resolve this issue? Thank you.

Environment: 
- FreeBSD 9.1
- Apache 2.4.28
- PHP 7.1.9 (I also confirmed with ver. 5.6) with GD, mbstring, curl, and PDO
- MySQL 5.5

**Comment by maskas** [comment]
if /admin without (.php) isn't  working, that mean mod_rewrite module is not present on your system. Not sure why you facing issues using admin.php.

**Comment by takugoishii** [comment]
Thank you Maskas, 
Before asking this, I thoutght mod_rewrite would be the source of the trouble and knew a piece of information that the web server I am using had mod_rewrite installed. I believed the information, but must servey a bit more now. I will try. Thank you for your comment, which let me focus on the point.

**Comment by takugoishii** [comment]
Resolved. 
I added “Options -MultiViews” on the top of .htaccess.
I knew that the server I am using turns MultiViews on as the default setting.
