### ISSUE TITLE
Minified files

### ISSUE THREAD

**Issue by epoxa** [impresspages/ImpressPages#882]
Hi guys!
A bit weird minified js/css files are included in the repo.
It assumes at least source config for minification/uglification tool should be attached too. But I can not find it out.
In particular, I optimized /Ip/Internal/Content/assets/management/jquery.ip.contentManagement.js for better performance. Now I need to update /Ip/Internal/Content/assets/management.min.js accordingly to make a pull request.
How should I do it correctly?
Thanks

**Comment by azanov** [comment]
Hi,

I had the same question some time ago. Check out this issue: https://github.com/impresspages/ImpressPages/issues/857
